services:
  # database
  mysql:
    image: mysql:8.0.39-debian
    container_name: mysql-sf_project_starter
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      # MYSQL_USER: root
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-sf_project_starter
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/
      PHP_MEMORY_LIMIT: 512M
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_POST_MAX_SIZE: 100M
      # PHP_TIMEZONE: #### YOUR TIMEZONE ####
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/var/www/html
      - ./public/uploads:/var/www/html/public/uploads
    depends_on:
      - mysql

  # nginx
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx-sf_project_starter
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # mailpit - mail testing service
  # mailpit:
  #   image: axllent/mailpit
  #   container_name: mailpit-sf_project_starter
  #   restart: unless-stopped
  #   volumes:
  #     - ./data:/data
  #   ports:
  #     - 8025:8025
  #     - 1025:1025
  #   environment:
  #     MP_MAX_MESSAGES: 5000
  #     MP_DATABASE: /data/mailpit.db
  #     MP_SMTP_AUTH_ACCEPT_ANY: 1
  #     MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  mysql-data: